/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kartkowka;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author G
 */
public class Kartkowka1 extends javax.swing.JFrame {

    /**
     * Creates new form Kartkówka1
     */
    public Kartkowka1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ko_jPanel = new javax.swing.JPanel();
        ko_jLabelInformacje = new javax.swing.JLabel();
        ko_jLabelTlo = new javax.swing.JLabel();
        ko_jLabelIleLat = new javax.swing.JLabel();
        ko_jComboBoxLat = new javax.swing.JComboBox<>();
        ko_jLabelGdzieU = new javax.swing.JLabel();
        ko_jRadioButtonMiasto = new javax.swing.JRadioButton();
        ko_jRadioButtonWies = new javax.swing.JRadioButton();
        ko_jLabelWaga = new javax.swing.JLabel();
        ko_jSlider = new javax.swing.JSlider();
        ko_jLabel = new javax.swing.JLabel();
        ko_jButtonWyślij = new javax.swing.JButton();
        ko_jMenuBarMenu = new javax.swing.JMenuBar();
        ko_jMenuPlik = new javax.swing.JMenu();
        ko_jMenuItemZapisz = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ko_jMenuItemWczytaj = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ko_jMenuItemZamknij = new javax.swing.JMenuItem();
        ko_jMenuEdycja = new javax.swing.JMenu();
        ko_jMenuItemTło = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        ko_jMenuItemczcionka = new javax.swing.JMenuItem();
        ko_jMenuoProgramie = new javax.swing.JMenu();
        ko_jMenuItemOProgra = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        ko_jMenuHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ko_jPanel.setBackground(new java.awt.Color(51, 255, 204));
        ko_jPanel.setForeground(new java.awt.Color(0, 204, 204));

        ko_jLabelInformacje.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ko_jLabelInformacje.setText("Krótkie informacje o tobie.");

        ko_jLabelTlo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ko_jLabelTloAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        ko_jLabelIleLat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_jLabelIleLat.setText("ILe masz lat?");

        ko_jComboBoxLat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5-10", "10-15", "15-20", "20-25" }));

        ko_jLabelGdzieU.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_jLabelGdzieU.setText("Gdzie się urodziłeś?");

        ko_jRadioButtonMiasto.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ko_jRadioButtonMiasto.setText("W mieśćie");

        ko_jRadioButtonWies.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ko_jRadioButtonWies.setText("Na wśi");

        ko_jLabelWaga.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_jLabelWaga.setText("Ile ważysz?");

        ko_jSlider.setMajorTickSpacing(10);
        ko_jSlider.setMinimum(10);
        ko_jSlider.setMinorTickSpacing(5);
        ko_jSlider.setPaintLabels(true);
        ko_jSlider.setPaintTicks(true);
        ko_jSlider.setSnapToTicks(true);
        ko_jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ko_jSliderStateChanged(evt);
            }
        });

        ko_jLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        ko_jLabel.setText("0");

        ko_jButtonWyślij.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ko_jButtonWyślij.setText("Wyślij");

        javax.swing.GroupLayout ko_jPanelLayout = new javax.swing.GroupLayout(ko_jPanel);
        ko_jPanel.setLayout(ko_jPanelLayout);
        ko_jPanelLayout.setHorizontalGroup(
            ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ko_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ko_jPanelLayout.createSequentialGroup()
                        .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ko_jLabelInformacje, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ko_jPanelLayout.createSequentialGroup()
                                .addComponent(ko_jLabelIleLat)
                                .addGap(39, 39, 39)
                                .addComponent(ko_jComboBoxLat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ko_jPanelLayout.createSequentialGroup()
                                .addComponent(ko_jLabelGdzieU, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ko_jRadioButtonMiasto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ko_jRadioButtonWies, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(ko_jLabelTlo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ko_jPanelLayout.createSequentialGroup()
                        .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ko_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ko_jPanelLayout.createSequentialGroup()
                                .addComponent(ko_jLabelWaga, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ko_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ko_jButtonWyślij, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ko_jPanelLayout.setVerticalGroup(
            ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ko_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ko_jLabelTlo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ko_jPanelLayout.createSequentialGroup()
                        .addComponent(ko_jLabelInformacje, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ko_jLabelIleLat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ko_jComboBoxLat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ko_jLabelGdzieU, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ko_jRadioButtonMiasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ko_jRadioButtonWies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(7, 7, 7)
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ko_jLabelWaga, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(ko_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ko_jButtonWyślij, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        ko_jMenuPlik.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ko_jMenuPlik.setText("Plik");

        ko_jMenuItemZapisz.setText("Zapisz");
        ko_jMenuPlik.add(ko_jMenuItemZapisz);
        ko_jMenuPlik.add(jSeparator1);

        ko_jMenuItemWczytaj.setText("Wczytaj");
        ko_jMenuPlik.add(ko_jMenuItemWczytaj);
        ko_jMenuPlik.add(jSeparator2);

        ko_jMenuItemZamknij.setText("Zamknij Program");
        ko_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jMenuItemZamknijActionPerformed(evt);
            }
        });
        ko_jMenuPlik.add(ko_jMenuItemZamknij);

        ko_jMenuBarMenu.add(ko_jMenuPlik);

        ko_jMenuEdycja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ko_jMenuEdycja.setText("Edycja");

        ko_jMenuItemTło.setText("Zmień Logo");
        ko_jMenuItemTło.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jMenuItemTłoActionPerformed(evt);
            }
        });
        ko_jMenuEdycja.add(ko_jMenuItemTło);
        ko_jMenuEdycja.add(jSeparator3);

        ko_jMenuItemczcionka.setText("Zmien Czcionkę");
        ko_jMenuItemczcionka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jMenuItemczcionkaActionPerformed(evt);
            }
        });
        ko_jMenuEdycja.add(ko_jMenuItemczcionka);

        ko_jMenuBarMenu.add(ko_jMenuEdycja);

        ko_jMenuoProgramie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ko_jMenuoProgramie.setText("O programie");

        ko_jMenuItemOProgra.setText("O Programie");
        ko_jMenuoProgramie.add(ko_jMenuItemOProgra);
        ko_jMenuoProgramie.add(jSeparator4);

        ko_jMenuHelp.setText("HELP");
        ko_jMenuoProgramie.add(ko_jMenuHelp);

        ko_jMenuBarMenu.add(ko_jMenuoProgramie);

        setJMenuBar(ko_jMenuBarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ko_jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ko_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ko_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ko_jMenuItemZamknijActionPerformed

    private void ko_jLabelTloAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ko_jLabelTloAncestorAdded
                ImageIcon icon = new ImageIcon("C:\\Users\\G\\Desktop\\ALL\\netbins\\logo.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(ko_jLabelTlo.getWidth(), ko_jLabelTlo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        ko_jLabelTlo.setIcon(scaledIcon);
     
    }//GEN-LAST:event_ko_jLabelTloAncestorAdded

    private void ko_jMenuItemTłoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jMenuItemTłoActionPerformed
              ImageIcon icon = new ImageIcon("C:\\Users\\G\\Desktop\\ALL\\netbins\\mes.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(ko_jLabelTlo.getWidth(), ko_jLabelTlo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        ko_jLabelTlo.setIcon(scaledIcon);
        
    }//GEN-LAST:event_ko_jMenuItemTłoActionPerformed

    private void ko_jMenuItemczcionkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jMenuItemczcionkaActionPerformed
      
    }//GEN-LAST:event_ko_jMenuItemczcionkaActionPerformed

    private void ko_jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ko_jSliderStateChanged
        ko_jLabel.setText(""+ko_jSlider.getValue());
    }//GEN-LAST:event_ko_jSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kartkowka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kartkowka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kartkowka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kartkowka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kartkowka1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JButton ko_jButtonWyślij;
    private javax.swing.JComboBox<String> ko_jComboBoxLat;
    private javax.swing.JLabel ko_jLabel;
    private javax.swing.JLabel ko_jLabelGdzieU;
    private javax.swing.JLabel ko_jLabelIleLat;
    private javax.swing.JLabel ko_jLabelInformacje;
    private javax.swing.JLabel ko_jLabelTlo;
    private javax.swing.JLabel ko_jLabelWaga;
    private javax.swing.JMenuBar ko_jMenuBarMenu;
    private javax.swing.JMenu ko_jMenuEdycja;
    private javax.swing.JMenuItem ko_jMenuHelp;
    private javax.swing.JMenuItem ko_jMenuItemOProgra;
    private javax.swing.JMenuItem ko_jMenuItemTło;
    private javax.swing.JMenuItem ko_jMenuItemWczytaj;
    private javax.swing.JMenuItem ko_jMenuItemZamknij;
    private javax.swing.JMenuItem ko_jMenuItemZapisz;
    private javax.swing.JMenuItem ko_jMenuItemczcionka;
    private javax.swing.JMenu ko_jMenuPlik;
    private javax.swing.JMenu ko_jMenuoProgramie;
    private javax.swing.JPanel ko_jPanel;
    private javax.swing.JRadioButton ko_jRadioButtonMiasto;
    private javax.swing.JRadioButton ko_jRadioButtonWies;
    private javax.swing.JSlider ko_jSlider;
    // End of variables declaration//GEN-END:variables
}
